### ISSUE TITLE
Bump the minor version from latest master

### ISSUE THREAD

**Issue by nezorflame** [astaxie/beego#3155]
We're using beego in our company with `golang/dep` dep manager.
It keeps getting the beego dependency at version `1.9.2` which has a fatal bug https://github.com/astaxie/beego/issues/2972 which is fixed in the latest `master` commit.
Please bump the version (i.e. to `1.9.3`) to include the latest fix.

**Comment by nezorflame** [comment]
@astaxie ping

**Comment by conero** [comment]
I met the same problem，but the author does not want to give answer，like.  So I use the dep code for that：
```toml
# github.com/astaxie/beego
[[constraint]]
name = "github.com/astaxie/beego"
#version = "1.11.1"
branch = "master"
source = "github.com/astaxie/beego"
```

but the GW tell me that ```master: unable to deduce repository and source type for "golang.org/x/crypto/acme/autocert": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://golang.org/x/crypto/acme/autocert?go-get=1": Get http://golang.org/x/crypto/acme/autocert?go-get=1: dial tcp 216.239.37.1:80: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.```. 

can somebody give me a hand, please and thank?
