### ISSUE TITLE
Use docker-compose to register db get error：register db Ping `default`, unknown time zone Asia/Shanghai

### ISSUE THREAD

**Issue by LampScript** [astaxie/beego#3800]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go and beego are you using (`bee version`)?

go version go1.12 darwin/amd64

______
| ___ \
| |_/ /  ___   ___
| ___ \ / _ \ / _ \
| |_/ /|  __/|  __/
\____/  \___| \___| v1.9.1

├── Beego     : 1.12.0
├── GoVersion : go1.13
├── GOOS      : darwin
├── GOARCH    : amd64
├── NumCPU    : 12
├── GOPATH    : /Users/miller/.go
├── GOROOT    : /usr/local/Cellar/go/1.13/libexec
├── Compiler  : gc
└── Date      : Sunday, 8 Sep 2019

2. What operating system and processor architecture are you using (`go env`)?
macOS Mojave 10.14.6

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
My docker-compose.yml is:
```
version: '3'
services:
  db:
#    image: mysql:5.7.27
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    restart: always
#    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0
    ports:
      - '3307:3306'
    expose:
      - "3307"
    volumes:
      - ./dockermysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=123456
      - MYSQL_USER=123456
      - MYSQL_PASSWORD=123456

  paperclip-bot:
    build: .
    command: ./main
    depends_on:
      - db
```
My mysql/Dockerfile is :
FROM mysql:5.7.27
ENV MYSQL_ROOT_PASSWORD=123456 MYSQL_DATABASE=miller MYSQL_USER=mysql_miller MYSQL_PASSWORD=123456 MYSQL_ALLOW_EMPTY_PASSWORD=True
RUN echo "USE mysql;" > /docker-entrypoint-initdb.d/timezones.sql &&  mysql_tzinfo_to_sql /usr/share/zoneinfo >> /docker-entrypoint-initdb.d/timezones.sql
EXPOSE 3306

My paperclip-bot: dockerfile has:
ENV TZ=Asia/Shanghai

My dsn is root:miller@tcp(db:3306)/123456?charset=utf8mb4&collation=utf8mb4_general_ci&loc=Asia%2FShanghai

My code is :
```
func NewPaperclipDao() {
	err := orm.RegisterDataBase("default", "mysql", config.Config.Dsn)
	if err != nil {
		panic(err.Error())
	}
	orm.RegisterModel(new(model.PaperclipJob))
	db := orm.NewOrm()

	PaperclipDao = &paperclipDao{
		Db: db,
	}
}
```

I use docker-compose up command to the project's root path, and has a panic "panic: register db Ping `default`, unknown time zone Asia/Shanghai", but I work it fine without docker.

4. What did you expect to see?

register table success

5. What did you see instead?
paperclip-bot_1  | [ORM]2019/09/08 09:56:56 register db Ping `default`, unknown time zone Asia/Shanghai
